<a href="https://colab.research.google.com/github/aot-abhishekyadav/Machine-Learning-Fundamentals/blob/main/15-HandlingDateAndTime/date-and-time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
date = pd.read_csv('/content/drive/MyDrive/orders.csv')
time = pd.read_csv('/content/drive/MyDrive/messages.csv')

In [ ]:
date.head(10)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3
5  2018-08-23        1811       25       4
6  2018-11-21        1282       26       1
7  2019-03-27        5022        2      41
8  2019-06-29        3699        3      15
9  2018-08-30        4373       11       3

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working With Dates

In [ ]:
# converting date into datetime datatype

date['date'] = pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract Year

In [ ]:
date['date_year'] = date['date'].dt.year  # using dt.Year we can extract Year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### 2. Extract Month

In [ ]:
date['date_month_no'] = date['date'].dt.month  # using dt.month we extract month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

3. Extract Month Name

In [ ]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

4. Extract Days

In [ ]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

5. name of the Day

In [ ]:
date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

6. Day Number

In [ ]:
date['date_week'] = date['date'].dt.dayofweek  # 0 . monday

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6

7. is weekend

In [ ]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_week,date_is_weekend
0,2019-12-10,2019,12,December,10,Tuesday,1,0
1,2018-08-15,2018,8,August,15,Wednesday,2,0
2,2018-10-23,2018,10,October,23,Tuesday,1,0
3,2019-08-17,2019,8,August,17,Saturday,5,1
4,2019-01-06,2019,1,January,6,Sunday,6,1

8. Extract Week Of the year

In [ ]:
date['date_week'] = date['date'].dt.isocalendar().week

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_week,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,50,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,33,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,43,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,33,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1

9. Extract Quarter

In [ ]:
date['quarter'] = date['date'].dt.quarter

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_week,date_is_weekend,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,50,0,4
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,33,0,3
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,43,0,4
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,33,1,3
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1,1

10. Extract Semester

In [ ]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_week,date_is_weekend,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,50,0,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,33,0,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,43,0,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,33,1,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1,1,1

11. Extract Time elapsed between dates

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 27, 8, 31, 54, 265525)

In [ ]:
today - date['date']

0     2421 days 08:31:54.265525
1     2903 days 08:31:54.265525
2     2834 days 08:31:54.265525
3     2536 days 08:31:54.265525
4     2759 days 08:31:54.265525
                 ...
995   2849 days 08:31:54.265525
996   2790 days 08:31:54.265525
997   2638 days 08:31:54.265525
998   2703 days 08:31:54.265525
999   2477 days 08:31:54.265525
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
#  Calculate in diff b/w present date and real date
(today - date['date']).dt.days

0      2421
1      2903
2      2834
3      2536
4      2759
       ...
995    2849
996    2790
997    2638
998    2703
999    2477
Name: date, Length: 1000, dtype: int64

In [ ]:
# Calculate difference in days and divide by average days in a month
np.round((today - date['date']).dt.days / 30.44, 0)

0      80.0
1      95.0
2      93.0
3      83.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    89.0
999    81.0
Name: date, Length: 1000, dtype: float64

# Working With Time

In [ ]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
# Converting object to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

1. Extract Hour

In [ ]:
time['hour'] = time['date'].dt.hour

time.head()

                 date                                                msg  hour
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37     0
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826    23
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576     0
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...     0
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше    23

2. Extract Minute

In [ ]:
time['min'] = time['date'].dt.minute

time.head()

,date,msg,hour,min
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11

3. Extract Seconds

In [ ]:
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

4. Extract Time Part

In [ ]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
time['time_year'] = time['date'].dt.year

In [ ]:
time['time_month'] = time['date'].dt.month
time['time_day'] = time['date'].dt.day

In [ ]:
time.head()

,date,msg,hour,min,sec,time,time_year,time_month,time_day
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00,2013,12,15
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00,2014,4,29
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00,2012,12,30
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00,2014,11,28
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00,2013,10,26

6. Time Differnce

In [ ]:
today - time['date']

0     4607 days 07:41:54.265525
1     4471 days 08:51:54.265525
2     4957 days 08:10:54.265525
3     4259 days 08:00:54.265525
4     4656 days 09:20:54.265525
                 ...
995   5246 days 07:41:54.265525
996   4567 days 09:17:54.265525
997   5032 days 08:54:54.265525
998   5148 days 08:57:54.265525
999   4420 days 09:06:54.265525
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# Diff in Seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.980725e+08
1      3.863263e+08
2      4.283143e+08
3      3.680065e+08
4      4.023121e+08
           ...
995    4.532821e+08
996    3.946223e+08
997    4.347969e+08
998    4.448195e+08
999    3.819208e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
# Diff in Minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.634542e+06
1      6.438772e+06
2      7.138571e+06
3      6.133441e+06
4      6.705201e+06
           ...
995    7.554702e+06
996    6.577038e+06
997    7.246615e+06
998    7.413658e+06
999    6.365347e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
# Diff in Hours

(today - time['date'])/np.timedelta64(1,'h')

0      110575.698407
1      107312.865074
2      118976.181740
3      102224.015074
4      111753.348407
           ...
995    125911.698407
996    109617.298407
997    120776.915074
998    123560.965074
999    106089.115074
Name: date, Length: 1000, dtype: float64

In [ ]:
# Months passed
np.round((today - time['date']).dt.days / 30.44, 0)

0      151.0
1      147.0
2      163.0
3      140.0
4      153.0
       ...
995    172.0
996    150.0
997    165.0
998    169.0
999    145.0
Name: date, Length: 1000, dtype: float64