<a href="https://colab.research.google.com/github/aot-abhishekyadav/Machine-Learning-Fundamentals/blob/main/04-Pandas/working_with_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# For jason files
import pandas as pd

In [ ]:
data = '{"name" : "Abhi", "email" : "abhi@gmail.com", "job_profile" :[{"title1" : "Team lead", "title2" : "jr Developer"}]}'

In [ ]:
type(data)

str

In [ ]:
pd.read_json(data)

/tmp/ipykernel_435/1661395064.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)

   name           email                                        job_profile
0  Abhi  abhi@gmail.com  {'title1': 'Team lead', 'title2': 'jr Developer'}

In [ ]:
pd.read_json(data, orient='records')

/tmp/ipykernel_435/1951668866.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data, orient='records')

   name           email                                        job_profile
0  Abhi  abhi@gmail.com  {'title1': 'Team lead', 'title2': 'jr Developer'}

In [ ]:
pd.read_json(data, orient = 'columns')

/tmp/ipykernel_435/1489559805.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data, orient = 'columns')

   name           email                                        job_profile
0  Abhi  abhi@gmail.com  {'title1': 'Team lead', 'title2': 'jr Developer'}

In [ ]:
# Both column ad records orient show dataframe like default mode

In [ ]:
pd.read_json(data, orient='index') # It make column into row and row into column

/tmp/ipykernel_435/3962022714.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data, orient='index') # It make column into row and row into column

                                                             0
name                                                      Abhi
email                                           abhi@gmail.com
job_profile  [{'title1': 'Team lead', 'title2': 'jr Develop...

In [ ]:
# Converting Dataframe into json
df = pd.DataFrame([['a' , 'b'] , ['c' , 'd']],
index = ['row1' , 'row2'],
columns = ['col1' , 'col2'])
df

     col1 col2
row1    a    b
row2    c    d

In [ ]:
df.to_json() # Converting into json

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [ ]:
df.to_json(orient = 'index') # High Priority is given to row

'{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}'

In [ ]:
df.to_json(orient = 'columns') # Print json like deafult mode high priority
                               # is given to columns

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [ ]:
df.to_json(orient = 'records') # High priority is given to columns and it ignores the row

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [ ]:
df.to_json(orient = 'split') # yai sab kaa alag alag data print karta hai

'{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
df.to_json(orient = 'table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [ ]:
schema = '{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [ ]:
pd.read_json(schema, orient='table')

/tmp/ipykernel_435/1255918773.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(schema, orient='table')

     col1 col2
row1    a    b
row2    c    d

In [ ]:
# Making data into normalize data
data = '{"name" : "Abhi", "email" : "abhi@gmail.com", "job_profile" :[{"title1" : "Team lead", "title2" : "jr Developer"}]}'
type(data)
# Abhi iska data type str hai phele hume iske data typeko str sai change kar kai list mai convert karna padegaa

str

In [ ]:
pd.read_json(data)

/tmp/ipykernel_435/1661395064.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)

   name           email                                        job_profile
0  Abhi  abhi@gmail.com  {'title1': 'Team lead', 'title2': 'jr Developer'}

In [ ]:
# staring aur closing dono mai square bracket laga diya hai jis sai ki yai data  list mai convert ho jaaye aur humne job profile kai pass sai bhi  square bracket hatya hai aur starting single koma bhi hata diya hai
data = [{"name" : "Abhi", "email" : "abhi@gmail.com", "job_profile" :{"title1" : "Team lead", "title2" : "jr Developer"}}]
type(data)

list

In [ ]:
# converting data inot normalize data
pd.json_normalize(data)

   name           email job_profile.title1 job_profile.title2
0  Abhi  abhi@gmail.com          Team lead       jr Developer

In [ ]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [ ]:
pd.json_normalize(data)

    id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [ ]:
pd.json_normalize(data, max_level = 0)
# Max level 0 pai vo nested list ko alg column mai separate nhi karta hai

    id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mark Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [ ]:
pd.json_normalize(data, max_level = 1)

    id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [ ]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [ ]:
pd.json_normalize(data)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [ ]:
pd.json_normalize(data, max_level = 0)

,state,shortname,info,counties
0,Florida,FL,{'governor': 'Rick Scott'},"[{'name': 'Dade', 'population': 12345}, {'name..."
1,Ohio,OH,{'governor': 'John Kasich'},"[{'name': 'Summit', 'population': 1234}, {'nam..."

In [ ]:
# using of record parameter
pd.json_normalize(data,"counties")
# counties ko print karne mai mushkil ho rhi thi isliye humne usse pehele alg sai print kara liya

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [ ]:
# using of meta parameter
pd.json_normalize(data,"counties" , ["state" , "shortname" , ["info" , "governor"]])
# meta ki help sai humne itne hard data ko easy way sai seprate kar kai print kar diya

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

In [ ]:
# Converting csv file into json file
df = pd.read_csv("/content/drive/MyDrive/coffee/coffee.pandas.csv")
df

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
df.to_json()

'{"Day":{"0":"Monday","1":"Monday","2":"Tuesday","3":"Tuesday","4":"Wednesday","5":"Wednesday","6":"Thursday","7":"Thursday","8":"Friday","9":"Friday","10":"Saturday","11":"Saturday","12":"Sunday","13":"Sunday"},"Coffee Type":{"0":"Espresso","1":"Latte","2":"Espresso","3":"Latte","4":"Espresso","5":"Latte","6":"Espresso","7":"Latte","8":"Espresso","9":"Latte","10":"Espresso","11":"Latte","12":"Espresso","13":"Latte"},"Units Sold":{"0":25,"1":15,"2":30,"3":20,"4":35,"5":25,"6":40,"7":30,"8":45,"9":35,"10":45,"11":35,"12":45,"13":35}}'

In [ ]:
df.to_json(orient = 'index')

'{"0":{"Day":"Monday","Coffee Type":"Espresso","Units Sold":25},"1":{"Day":"Monday","Coffee Type":"Latte","Units Sold":15},"2":{"Day":"Tuesday","Coffee Type":"Espresso","Units Sold":30},"3":{"Day":"Tuesday","Coffee Type":"Latte","Units Sold":20},"4":{"Day":"Wednesday","Coffee Type":"Espresso","Units Sold":35},"5":{"Day":"Wednesday","Coffee Type":"Latte","Units Sold":25},"6":{"Day":"Thursday","Coffee Type":"Espresso","Units Sold":40},"7":{"Day":"Thursday","Coffee Type":"Latte","Units Sold":30},"8":{"Day":"Friday","Coffee Type":"Espresso","Units Sold":45},"9":{"Day":"Friday","Coffee Type":"Latte","Units Sold":35},"10":{"Day":"Saturday","Coffee Type":"Espresso","Units Sold":45},"11":{"Day":"Saturday","Coffee Type":"Latte","Units Sold":35},"12":{"Day":"Sunday","Coffee Type":"Espresso","Units Sold":45},"13":{"Day":"Sunday","Coffee Type":"Latte","Units Sold":35}}'

In [ ]:
df.to_json(orient = 'records')

'[{"Day":"Monday","Coffee Type":"Espresso","Units Sold":25},{"Day":"Monday","Coffee Type":"Latte","Units Sold":15},{"Day":"Tuesday","Coffee Type":"Espresso","Units Sold":30},{"Day":"Tuesday","Coffee Type":"Latte","Units Sold":20},{"Day":"Wednesday","Coffee Type":"Espresso","Units Sold":35},{"Day":"Wednesday","Coffee Type":"Latte","Units Sold":25},{"Day":"Thursday","Coffee Type":"Espresso","Units Sold":40},{"Day":"Thursday","Coffee Type":"Latte","Units Sold":30},{"Day":"Friday","Coffee Type":"Espresso","Units Sold":45},{"Day":"Friday","Coffee Type":"Latte","Units Sold":35},{"Day":"Saturday","Coffee Type":"Espresso","Units Sold":45},{"Day":"Saturday","Coffee Type":"Latte","Units Sold":35},{"Day":"Sunday","Coffee Type":"Espresso","Units Sold":45},{"Day":"Sunday","Coffee Type":"Latte","Units Sold":35}]'

In [ ]:
df.to_json(orient = 'columns')

'{"Day":{"0":"Monday","1":"Monday","2":"Tuesday","3":"Tuesday","4":"Wednesday","5":"Wednesday","6":"Thursday","7":"Thursday","8":"Friday","9":"Friday","10":"Saturday","11":"Saturday","12":"Sunday","13":"Sunday"},"Coffee Type":{"0":"Espresso","1":"Latte","2":"Espresso","3":"Latte","4":"Espresso","5":"Latte","6":"Espresso","7":"Latte","8":"Espresso","9":"Latte","10":"Espresso","11":"Latte","12":"Espresso","13":"Latte"},"Units Sold":{"0":25,"1":15,"2":30,"3":20,"4":35,"5":25,"6":40,"7":30,"8":45,"9":35,"10":45,"11":35,"12":45,"13":35}}'

In [ ]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR') # url kai liye direct url daal do

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.6740
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.8620
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,3.8600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.1930
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.2820